AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    5a49fac4-991e-4070-916c-5e2a0b1311bd:
      size:
        width: 60
        height: 60
      position:
        x: 198
        'y': 99
      z: 0
      embeds: []
    fef8a509-ced8-430b-81d1-a353eb3cbb59:
      size:
        width: 60
        height: 60
      position:
        x: 315
        'y': 97
      z: 0
      embeds: []
    b943b41c-78a1-4c80-b3ab-ea3c57fca06f:
      size:
        width: 60
        height: 60
      position:
        x: 461
        'y': 104
      z: 0
      embeds: []
    f135fd8f-ac4f-48ab-8ad3-5625d0c5d2ad:
      size:
        width: 60
        height: 60
      position:
        x: 586
        'y': 105
      z: 0
      embeds: []
      dependson:
        - fef8a509-ced8-430b-81d1-a353eb3cbb59
        - b943b41c-78a1-4c80-b3ab-ea3c57fca06f
    355e45e0-9d36-49a7-8d8d-fc3b7f760b9c:
      size:
        width: 60
        height: 60
      position:
        x: 708
        'y': 99
      z: 0
      embeds: []
    1453d6ad-0801-4957-a2f6-c9cc5887b06b:
      size:
        width: 60
        height: 60
      position:
        x: 843
        'y': 100
      z: 0
      embeds: []
      dependson:
        - b943b41c-78a1-4c80-b3ab-ea3c57fca06f
Resources:
  RDSDBI32QQE:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 10
      Engine: MySQL
      MasterUsername: admin
      MasterUserPassword: Naveen1999
      DBInstanceClass: db.t2.micro
      DBName: cmsdb
      DBInstanceIdentifier: rds12
      VPCSecurityGroups:
        - sg-0b947349537e69ed2
      EngineVersion: 5.7
      PubliclyAccessible: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5a49fac4-991e-4070-916c-5e2a0b1311bd
  ELBV2LB1HUDC:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: my-load-balancer-new3
      Subnets:
        - subnet-010656811f3381d92
        - subnet-026d1c34b85e10605
      IpAddressType: ipv4
    Metadata:
      'AWS::CloudFormation::Designer':
        id: fef8a509-ced8-430b-81d1-a353eb3cbb59
  ELBV2TG4A6L0:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: my-target-group-new3
      Port: 80
      Protocol: HTTP
      VpcId: vpc-01ac3cdf74d6afae6
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b943b41c-78a1-4c80-b3ab-ea3c57fca06f
  ELBV2L42QE:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref ELBV2LB1HUDC
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ELBV2TG4A6L0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f135fd8f-ac4f-48ab-8ad3-5625d0c5d2ad
    DependsOn:
      - ELBV2LB1HUDC
      - ELBV2TG4A6L0
  ASLC55LJA:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      LaunchConfigurationName: my-lc-new3
      ImageId: ami-04505e74c0741db8d
      InstanceType: t2.micro
      IamInstanceProfile: demo-Role
      KeyName: Naveen06training
      SecurityGroups:
        - sg-0b947349537e69ed2
      UserData:
        'Fn::Base64': !Sub 
            |
            #!/bin/bash
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install apache2 -y
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 355e45e0-9d36-49a7-8d8d-fc3b7f760b9c
  ASASG3CEB8:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: my-asg-new3
      LaunchConfigurationName: my-lc-new3
      AvailabilityZones:
        - us-east-1d
        - us-east-1c
      DesiredCapacity: 2
      MaxSize: 3
      MinSize: 2
      TargetGroupARNs:
        - !Ref ELBV2TG4A6L0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1453d6ad-0801-4957-a2f6-c9cc5887b06b
    DependsOn:
      - ELBV2TG4A6L0
